#!/usr/bin/env bash
#
# Cloudflare Tunnel setup for AI Mining OS.
#
# Replaces ngrok with a stable HTTPS URL pointing at the locally-running
# backend on port 8000. Named tunnels require a domain you own on the same
# Cloudflare account; use --quick for a temporary trycloudflare.com URL.
#
# Usage:
#   ./deployment/cloudflared_setup.sh --domain your-domain.com [--tunnel aios-api] [--subdomain aios-api]
#   ./deployment/cloudflared_setup.sh --quick
#   ./deployment/cloudflared_setup.sh --help
#
# On success it writes the public URL into backend/.env (BASE_URL + CORS)
# and frontend/.env (VITE_API_URL), then prints the URL to use on Vercel.
#
set -euo pipefail

TUNNEL_NAME="aios-api"
SUBDOMAIN="aios-api"
DOMAIN=""
MODE="named"
BACKEND_HOST="127.0.0.1"
BACKEND_PORT="8000"
CLOUDFLARED_VERSION="2025.4.0"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

log()  { printf '\033[1;36m[cloudflared]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[cloudflared]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[cloudflared]\033[0m %s\n' "$*" >&2; exit 1; }

usage() {
    sed -n '2,16p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    exit 0
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --domain)   DOMAIN="${2:-}"; shift 2 ;;
        --tunnel)   TUNNEL_NAME="${2:-}"; shift 2 ;;
        --subdomain) SUBDOMAIN="${2:-}"; shift 2 ;;
        --quick)    MODE="quick"; shift ;;
        --help|-h)  usage ;;
        *) die "Unknown argument: $1 (see --help)" ;;
    esac
done

install_cloudflared() {
    if command -v cloudflared >/dev/null 2>&1; then
        log "cloudflared already installed: $(cloudflared --version)"
        return 0
    fi

    log "Installing cloudflared..."
    local os arch url
    os="$(uname -s)"
    arch="$(uname -m)"

    case "$os" in
        Darwin)
            command -v brew >/dev/null 2>&1 || die "Homebrew required to install cloudflared on macOS"
            brew install cloudflared
            ;;
        Linux)
            case "$arch" in
                x86_64)  arch="amd64" ;;
                aarch64|arm64) arch="arm64" ;;
                *) die "Unsupported architecture: $arch" ;;
            esac
            url="https://github.com/cloudflare/cloudflared/releases/download/${CLOUDFLARED_VERSION}/cloudflared-linux-${arch}"
            sudo curl -L "$url" -o /usr/local/bin/cloudflared
            sudo chmod +x /usr/local/bin/cloudflared
            ;;
        *) die "Unsupported OS: $os (install cloudflared manually)" ;;
    esac
    log "Installed: $(cloudflared --version)"
}

check_backend() {
    if ! curl -sf --max-time 3 "http://${BACKEND_HOST}:${BACKEND_PORT}/health" >/dev/null 2>&1; then
        warn "Backend not reachable at http://${BACKEND_HOST}:${BACKEND_PORT}/health"
        warn "Start it first: uvicorn backend.main:app --host 0.0.0.0 --port ${BACKEND_PORT}"
    else
        log "Backend health check passed."
    fi
}

login() {
    if [[ ! -f "$HOME/.cloudflared/cert.pem" ]]; then
        log "Opening browser for Cloudflare login..."
        cloudflared tunnel login || die "Login failed. Run 'cloudflared tunnel login' manually."
    else
        log "Cloudflare credentials found (~/.cloudflared/cert.pem)."
    fi
}

tunnel_exists() {
    cloudflared tunnel list --output json 2>/dev/null | grep -q "\"name\":\"${TUNNEL_NAME}\""
}

write_config() {
    local cfg="$HOME/.cloudflared/config.yml"
    mkdir -p "$HOME/.cloudflared"
    cat > "$cfg" <<EOF
# Auto-generated by deployment/cloudflared_setup.sh
tunnel: ${TUNNEL_ID}
credentials-file: $HOME/.cloudflared/${TUNNEL_ID}.json

ingress:
  - hostname: ${PUBLIC_HOST}
    service: http://${BACKEND_HOST}:${BACKEND_PORT}
  - service: http_status:404
EOF
    log "Wrote $cfg"
}

upsert_env() {
    local file="$1" key="$2" value="$3"
    [[ -f "$file" ]] || touch "$file"
    if grep -qE "^${key}=" "$file"; then
        sed -i.bak "s|^${key}=.*|${key}=${value}|" "$file"
    else
        printf '\n%s=%s\n' "$key" "$value" >> "$file"
    fi
}

apply_named_tunnel() {
    [[ -n "$DOMAIN" ]] || die "Missing --domain. Named tunnels require a domain on your Cloudflare account."
    PUBLIC_HOST="${SUBDOMAIN}.${DOMAIN}"
    PUBLIC_URL="https://${PUBLIC_HOST}"

    login

    if ! tunnel_exists; then
        log "Creating tunnel '$TUNNEL_NAME'..."
        cloudflared tunnel create "$TUNNEL_NAME" >/dev/null
    fi
    TUNNEL_ID="$(cloudflared tunnel list --output json | python3 -c "import sys,json; d=json.load(sys.stdin); print([t['id'] for t in d if t['name']=='${TUNNEL_NAME}'][0])")"
    log "Tunnel ID: ${TUNNEL_ID}"

    write_config

    if cloudflared tunnel route dns "$TUNNEL_NAME" "$PUBLIC_HOST" 2>/dev/null; then
        log "DNS route ${PUBLIC_HOST} -> tunnel created."
    else
        warn "DNS route failed. Ensure '$DOMAIN' is added as a zone in your Cloudflare account (dash.cloudflare.com)."
        warn "Re-run: cloudflared tunnel route dns $TUNNEL_NAME $PUBLIC_HOST"
    fi

    log "Installing tunnel as a background service..."
    cloudflared service install 2>/dev/null || {
        warn "Could not install service automatically; starting in foreground instead."
        nohup cloudflared tunnel --config "$HOME/.cloudflared/config.yml" run "$TUNNEL_NAME" \
            >> /tmp/cloudflared.log 2>&1 &
    }
}

apply_quick_tunnel() {
    warn "Quick tunnel gives a RANDOM URL on every restart (same problem as ngrok)."
    warn "For a stable URL, use --domain and a Cloudflare zone."
    PUBLIC_URL=""
    nohup cloudflared tunnel --url "http://${BACKEND_HOST}:${BACKEND_PORT}" \
        --no-autoupdate >> /tmp/cloudflared.log 2>&1 &
    log "Waiting for quick tunnel URL..."
    for _ in $(seq 1 15); do
        PUBLIC_URL="$(grep -oE 'https://[a-z0-9-]+\.trycloudflare\.com' /tmp/cloudflared.log | tail -1 || true)"
        [[ -n "$PUBLIC_URL" ]] && break
        sleep 1
    done
    [[ -n "$PUBLIC_URL" ]] || die "Could not detect quick tunnel URL. Check /tmp/cloudflared.log"
    PUBLIC_HOST="$(echo "$PUBLIC_URL" | sed 's|https://||')"
}

# ---------------------------------------------------------------- main
install_cloudflared
check_backend

if [[ "$MODE" == "quick" ]]; then
    apply_quick_tunnel
else
    apply_named_tunnel
fi

log "Public URL: ${PUBLIC_URL}"

# Auto-wire the backend and frontend to the Cloudflare URL (ngrok replacement)
upsert_env "$REPO_ROOT/.env"      "BASE_URL"   "$PUBLIC_URL"
upsert_env "$REPO_ROOT/frontend/.env" "VITE_API_URL" "$PUBLIC_URL"

# Allow the frontend origin through CORS (backend keeps localhost dev origins too)
CORS_NOW="$(grep -E '^CORS_ORIGINS=' "$REPO_ROOT/.env" 2>/dev/null | cut -d= -f2- || true)"
if [[ -n "$CORS_NOW" ]]; then
    if ! echo "$CORS_NOW" | grep -q "$PUBLIC_URL"; then
        upsert_env "$REPO_ROOT/.env" "CORS_ORIGINS" "${CORS_NOW},${PUBLIC_URL}"
    fi
else
    upsert_env "$REPO_ROOT/.env" "CORS_ORIGINS" "http://localhost:5173,http://localhost:3000,${PUBLIC_URL}"
fi

log "Updated backend/.env  -> BASE_URL, CORS_ORIGINS"
log "Updated frontend/.env -> VITE_API_URL=${PUBLIC_URL}"
log ""
log "Next steps:"
log "  1. Restart the backend (uvicorn backend.main:app --host 0.0.0.0 --port ${BACKEND_PORT})"
log "  2. Set VITE_API_URL=${PUBLIC_URL} in the Vercel dashboard and redeploy the frontend"
log "  3. Verify: curl ${PUBLIC_URL}/health"
log "  4. Done — ngrok is no longer needed."
